name: Ubuntu VNC

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Desktop Environment & VNC
        run: |
          sudo apt update
          sudo apt install xfce4 xfce4-goodies tightvncserver git -y
          
          # إنشاء مجلد .vnc
          mkdir -p ~/.vnc
          
          # تعيين كلمة المرور بشكل تلقائي
          echo "StrongPass123" | vncpasswd -f > ~/.vnc/passwd
          chmod 600 ~/.vnc/passwd
          
          # ملف بدء التشغيل
          echo "#!/bin/bash
          xrdb $HOME/.Xresources
          startxfce4 &" > ~/.vnc/xstartup
          chmod +x ~/.vnc/xstartup
          
          # تشغيل VNC
          vncserver :1 -geometry 1280x720 -depth 24

      - name: Setup noVNC Server
        run: |
          git clone https://github.com/novnc/noVNC.git ~/noVNC
          git clone https://github.com/novnc/websockify ~/noVNC/utils/websockify
          nohup ~/noVNC/utils/launch.sh --vnc localhost:5901 --listen 6080 &
          sleep 10
          nohup ssh -o StrictHostKeyChecking=no -R 80:localhost:6080 serveo.net > serveo.log 2>&1 &
          sleep 10
          echo "========== رابط الدخول =========="
          grep -o "https://[0-9a-zA-Z.-]*serveo.net" serveo.log || echo "تعذر الحصول على الرابط"
